# Cloudflare Worker with Browser Rendering binding

name = "browser-rendering-api"
main = "puppeteer-worker.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Configure the Browser Rendering binding
[browser]
binding = "browser"
